/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A market-impact backtest driven by JSON commands. */
export declare class Impact {
  /**
   * Construct a backtest handle from a spec JSON (`"{}"` defers configuration
   * to a later `set_spec` command). Throws on an invalid spec.
   */
  constructor(specJson: string)
  /**
   * Apply a command envelope (`{"cmd":"...", ...}`) and return the response
   * JSON. Commands: `set_spec`, `run`, `version`.
   */
  command(cmdJson: string): string
  /** The crate version. */
  version(): string
}
